### ISSUE TITLE
Alpha Maps export flaws

### ISSUE THREAD

**Issue by Arnfild** [Kruithne/wow.export#129]
1) .csv file containing information about texture layers per chunk should be exported with the alphamaps. With no this information alphamaps export makes little sense
2) Naming of the alphamaps should be locationName_tileNumber_chunkNumber instead of tex_tileNumber_chunkNumber. There are various cases when several tiles and their textures are merged in one folder. For example, when importing to 3D Software / Engines. There are tiles from different zones which have equal numbers. Let's take 35_33 or any other random number, such tile exists at least both in Kalimdor and Eastern Kingdoms

**Comment by Kruithne** [comment]
1. That is planned, the addition of exporting alpha maps in the current state was a simple PoC to get them in people's hands, it's not a finished feature yet. We don't have a beta branch so prototype features will show up from time to time.

2. That would diverge from how we name things in every other case. We don't rename textures per map, since they're stored inside a relative folder. May be something we look into adjusting this, but likely a separate issue to this.
