### ISSUE TITLE
Add ability to replace textures on models

### ISSUE THREAD

**Issue by QartemisT** [Kruithne/wow.export#280]
It would be nice if we could have a feature added to the current menu that appears when you click a texture, to be able to replace it with a different one.

**Comment by Kruithne** [comment]
Reassigning textures would only affect OBJ/GLTF exports, which could just be reassigned in whatever the target 3D software (such as Blender). It would not affect raw M2 exports since those are directly exported and we do not modify them in any way.

With that in mind, I think this falls outside the scope of wow.export
