### ISSUE TITLE
Include Position inside the WMOs and other meshes like Tileset

### ISSUE THREAD

**Issue by NUTTREX** [Kruithne/wow.export#319]
I'm not sure if a use case is needed for this but I'm trying to import things separately for example Tilesets scene positions are fine! and work wonders but when importing wmos etc it doesn't include it's scene position which makes it harder having to go through bunch of CSV to find a position of a mesh. I'm sure nobody else have this issue but id be cool to add this to even the backlog :D

**Comment by Kruithne** [comment]
Unsure what this means. WMOs and M2 models (assuming that's what you meant by "other models") don't have their own positions because they can appear in any location.

In order to do this, we'd have to export each instance of a WMO to a different file, which would inflate export sizes beyond reason. We can't write the position to the model file, because it could appear five times in different locations.

For these reasons, we include all of the models in a placement CSV file which you can parse in your pipeline. Closing this, since we won't be changing it.
