### ISSUE TITLE
Remove Vue from the project

### ISSUE THREAD

**Issue by Kruithne** [Kruithne/wow.export#349]
Currently our UI relies on the reactive framework Vue. While there are benefits to this, I've decided to remove it from the codebase for the following reasons:

- A lot of the functionality of the UI can be implemented in a much simpler manner without the need for a reactive framework.
- Vue adds a considerably large amount of code to the final bundle.
- Currently numerous shims are required for Vue to work along with additional build variables.
- Components are more complicated than they need to be.
- Vue currently conflicts with Bun and requires a hack-fix in the build pipeline.

**Comment by davidrios** [comment]
Are you against the idea of using another framework in place of Vue? I've been using this one at work and it's pretty good: https://lit.dev/

**Comment by Kruithne** [comment]
That's interesting, I hadn't heard of that one before but I'll give it a look, I'm currently using Vue for a number of projects at work, so this might be a fit there. As for wow.export, this issue is stale and was created when we were making large refactors on the codebase, which we're not doing anymore.

As much as there are some pain points with Vue (or more-so with how we've used it in this project), we're not going to commit the time to make a refactor like this when it's not causing any major issues with the functionality of the software and it's not blocking any outstanding issues.

Going to close this issue as out-of-date.

**Comment by davidrios** [comment]
That makes sense. I quite like Vue actually, but I've mainly used v3 with SFC and composition API, so I probably got a much better experience. The only reason I chose Lit instead at work was because it was an existing standard server-side rendered HTML page using basic standalone scripts doing manual DOM manipulation with jQuery, no build process for front-end, etc, basically a very old-style style application, so integrating Vue was not really feasible. I needed to implement some complex components though, and jQuery wouldn't really cut it (and I'm not about to seriously use it in 2024), so I found this Lit guy and used it to great success. I really recommend it if you need to incrementally add complex components to an existing project.
