### ISSUE TITLE
为什么一定要在线加载呢

### ISSUE THREAD

**Issue by jihuxiang1geshenshi** [Kruithne/wow.export#425]
你们做的这个程序真的很厉害，能关联到一个M2文件的相关下载到全部文件，只是很不理解的是为什么要在线读取listfile呢？我不知道你们的机制是什么，但是每次读取listfile的时候似乎都很担心读取不了，事实上真的是很多时候都没法成功读取listfile,就卡在这一项，实际上是可以将listfile下载到本地来方便以后读取的，这样至少不会影响每次开启时的读取困难。

**Comment by Marlamin** [comment]
EN:
wow.export requires an internet connection because database definitions and listfile names can change between builds and some files might not be downloaded by battle.net and need to be streamed in. You can download the listfile [manually](https://github.com/wowdev/wow-listfile/releases) (community-listfile.csv) and change the listfile URL in settings to point to the file location on disk, but new models, textures and other files would not be added after new patches/things are released.

CN:
wow.export 需要网络连接，因为数据库定义和列表文件名称在版本之间可能会发生变化，并且某些文件可能无法通过 battle.net 下载，需要流式传输。您可以[手动](https://github.com/wowdev/wow-listfile/releases) (community-listfile.csv) 下载列表文件并在设置中更改列表文件 URL 以指向磁盘上的文件位置，但在发布新补丁/内容后，不会添加新模型、纹理和其他文件。
