### ISSUE TITLE
Allow usage of offline CSV listfile

### ISSUE THREAD

**Issue by thunderysteak** [Kruithne/wow.export#81]
Currently the tool relies only on wow.tools site to function, and if for some reason the site is down, the user cannot reach the site or the cache is too old, CASC initialization will fail as it cannot update the listfile.

```[13:22:30] Loaded 1290221 entries from 32 journal indexes (3722ms)
[13:22:38] Parsed encoding table (1585762 entries) (7892ms)
[13:22:45] Parsed root file (934531 entries, 861 types) (6606ms)
[13:22:45] Loading listfile for build b1bb4de2fb624c4c3fb323f5ed1d0824
[13:22:45] Listfile for b1bb4de2fb624c4c3fb323f5ed1d0824 is not cached, downloading fresh.
[13:22:45] Failed to load CASC: Error: getaddrinfo ENOTFOUND wow.tools
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26) {
  [stack]: 'Error: getaddrinfo ENOTFOUND wow.tools\n' +
    '    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26)',
  [message]: 'getaddrinfo ENOTFOUND wow.tools',
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'wow.tools'
}```

**Comment by Kruithne** [comment]
0.1.7 introduces two changes to address this.

- If a listfile cannot be downloaded remotely, but an out-dated version is still available in the cache, it will revert to using that as a redundancy rather than failing with an error. If the download fails, but there is no valid version cached, the error will still be thrown.
- Users can now manually set the listfile source (in settings) to point to a local file location. If a local listfile location is set, no updating will be done and users will need to manage listfiles themselves. As wow.export supports different builds, local listfiles can be separated by build IDs the same way we internally cache them. This is done using the `%s` notation in the path. For example, `D:\listfiles\%s\listfile.txt` will resolve to `D:\listfiles\d987e36d3d50c61a55ef4a84bae915ec\listfile.txt` with the build ID varying per build. To use a single master listfile for everything, the `%s` can be omitted (e.g `D:\listfiles\listfile.txt`).
